version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./code:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./code:/var/www/
    working_dir: /var/www/